NDefines.NGame.START_DATE = "3018.1.1.12"
NDefines.NGame.END_DATE = "4018.1.1.1"
NDefines.NGame.HANDS_OFF_START_TAG = "RHD"

-- AI hire advisors behaviour
NDefines.NAI.HIGH_COMMAND_ADDED_WEIGHT_FACTOR = 0.5	-- Weight multiplier for high_command advisors over other chosen advisor or idea types
NDefines.NAI.CHIEF_ADDED_WEIGHT_FACTOR = 1.0			-- Weight multiplier for chief roles over other advisor or idea types
NDefines.NAI.ADVISOR_SCORE_CHEAPER_IS_BETTER_FACTOR = 0.5  -- When scoring advisors, this define scales how much the AI prefers cheaper advisors over more expensive ones. 0.0 means no effect, 0.15 means a cost difference of 100 PP modifies the score by 15 %.
NDefines.NAI.DESIGN_COMPANY_SCORE_MULTIPLIER = 1.25              -- score multiplier for hiring a design company
NDefines.NAI.ARMY_CHIEF_SCORE_MULTIPLIER = 0.75                  -- score multiplier for hiring an army chief
NDefines.NAI.AIR_CHIEF_SCORE_MULTIPLIER = 1.0                   -- score multiplier for hiring an air chief
NDefines.NAI.POLITICAL_ADVISOR_SCORE_MULTIPLIER = 1.25           -- score multiplier for hiring political advisors
NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 2.3
NDefines.NDeployment.BASE_DEPLOYMENT_TRAINING = 2
-- Less civs required for agency
NDefines.NOperatives.AGENCY_CREATION_FACTORIES = 3					-- Number of factories used to create an intelligence agency
NDefines.NOperatives.BECOME_SPYMASTER_PP_COST = 25
NDefines.NOperatives.BOOST_IDEOLOGY_DAILY_XP_GAIN	= 0.05
NDefines.NOperatives.PROPAGANDA_DAILY_XP_GAIN	= 0.005

-- Advisor and general changes
NDefines.NCharacter.OFFICER_CORP_ADVISOR_ENTRIES_IN_MENU = { "high_command", "theorist", "army_chief", "cavalry_chief", "navy_chief" }
NDefines.NCharacter.OFFICER_CORP_HIGH_COMMAND_SLOTS_IN_MENU = 2 --For Alert manager to count the number of High Command Slots in the UI
NDefines.NCharacter.POLITICAL_ADVISOR_SLOTS_IN_MENU = 2 --For Alert manager to count the number of Political Advisor Slots in the UI
NDefines.NCharacter.DEFAULT_PP_COST_FOR_MILITARY_ADVISOR = 125	-- When an advisor does not have cost assigned this is the default used	
NDefines.NCharacter.SPECIALIST_ADVISOR_MIN_RANK = 3
NDefines.NCharacter.EXPERT_ADVISOR_MIN_RANK = 5

NDefines.NCharacter.GENIUS_ADVISOR_MIN_RANK = 7
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 20       
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.52
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.15

-- lowered minimum land-unit speed
NDefines.NMilitary.SLOWEST_SPEED = 4

-- single fort = encampment. Castle = 7 forts
NDefines.NMilitary.BASE_FORT_PENALTY = -0.05

-- Airbase lower capacity
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 10

-- Max slots shared by factories
NDefines.NBuildings.MAX_SHARED_SLOTS = 99


-- Shore bombardment buff (this is 3x vanilla)
NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.75
NDefines.NNavy.HEAVY_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.3  -- heavy gun attack value is divided by this value * 100 and added to shore bombardment modifier
NDefines.NNavy.LIGHT_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.15 -- light gun attack value is divided by this value * 100 and added to shore bombardment modifier

-- Civilian factories per line lowered
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 12

-- Tension related defines
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 15							-- Amount of tension generated by a no-CB wargoal : base value 15
NDefines.NDiplomacy.TENSION_CB_WAR = 6								-- Amount of tension generated by a war with a CB : base value 7
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "3018.1.1.12"	-- Starting at this date, the tension values will be scaled down (will be equal to 1 before that)

-- Better supply from motorization
NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_BONUS = 3.0

-- Lowering attrition damage
NDefines.NSupply.SUPPLY_THRESHOLD_FOR_ARMY_ATTRITION = 0.28        -- at 28% supply army starts to suffer attrition
NDefines.NMilitary.ATTRITION_DAMAGE_ORG = 0.07					   -- damage from attrition to Organisation
NDefines.NMilitary.ATTRITION_EQUIPMENT_LOSS_CHANCE = 0.05		   -- Chance for loosing equipment when suffer attrition. Scaled up the stronger attrition is. Then scaled down by equipment reliability.
NDefines.NMilitary.ATTRITION_EQUIPMENT_PER_TYPE_LOSS_CHANCE = 0.05 -- Chance for loosing equipment when suffer attrition. Scaled up the stronger attrition is. Then scaled down by equipment reliability.
NDefines.NMilitary.ATTRITION_WHILE_MOVING_FACTOR = 0.75



-- Increased XP gain from training air-wings (because we have so few planes)
NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.15
NDefines.NAir.AIR_WING_XP_AIR_VS_AIR_COMBAT_GAIN = 8.0
NDefines.NAir.AIR_WING_XP_GROUND_MISSION_COMPLETED_GAIN = 2.8
NDefines.NAir.AIR_WING_XP_RECON_MISSION_COMPLETED_GAIN = 0.5
NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 1000					-- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 1000
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 1000
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 8000
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 1000
NDefines.NAir.AIR_WING_MAX_SIZE = 100 							-- Max amount of airplanes in wing
NDefines.NAir.AIR_WING_AVERAGE_SIZE = 10 						-- Eyeballed average amount of airplanes in wing. Used when calculating air volunteer.
NDefines.NAir.MANPOWER_LOSS_RATIO_PLANE_SHOT = 1.0
NDefines.NAir.AI_ALLOWED_PLANES_KEPT_IN_RESERVE = 0.0
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.6          -- effect on defense due to enemy air superiorty
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE = 0.80	       -- more AA attack will approach this amount of help (diminishing returns)
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 112 -- how quickly defense approaches the max impact diminishing returns curve
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.5     -- effect on speed due to enemy air superiority

-- Increased army XP from training units (slightly)
NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0025

-- AI template unit management related
NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 5
NDefines.NAI.WANTED_UNITS_MANPOWER_DIVISOR = 2100
-- NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.03
NDefines.NAI.WANTED_UNITS_WEIGHT_FRONTS_WANT = 0.45
NDefines.NAI.WANTED_UNITS_WEIGHT_MANPOWER = 0.3
NDefines.NAI.WANTED_UNITS_WEIGHT_FACTORIES = 0.3                        -- Weight of military factories when computing final nr wanted units
NDefines.NAI.WANTED_UNITS_MIN_DEFENCE_FACTOR = 0.7
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 28       -- Recalculate desired best template to upgrade with this many days inbetween.
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_LAND_EQUIPMENT = 1.5  -- How quickly is desire to update/create land equipment variants accumulated?
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 3.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_AIR_EQUIPMENT = 0.2
NDefines.NAI.DESIRE_USE_XP_TO_UPDATE_LAND_TEMPLATE = 8.0    -- How quickly is desire to update/create templates accumulated?

NDefines.NAI.WANTED_UNITS_THREAT_BASE = 0.8                             -- If no threat, multiply min wanted units by this
NDefines.NAI.WANTED_UNITS_THREAT_MAX = 3.0                             -- Normalized threat is clamped to this
NDefines.NAI.WANTED_UNITS_WAR_THREAT_FACTOR = 1.15                       -- Factor threat with this if country is at war. this value is overriden by the value in ideology database if that value exceedes this.
NDefines.NAI.WANTED_UNITS_DANGEROUS_NEIGHBOR_FACTOR = 1.15              -- Factor if has dangerous neighbor

NDefines.NAI.WANTED_UNITS_MAX_WANTED_CAP = 300	-- Maximum wanted divisions for a country. This can be exceeded by certain hardcoded multipliers, but not by base calculation logic.
NDefines.NAI.AT_WAR_THREAT_FACTOR = 1.7					-- How much increase in threat does AI feel for being in war against someone
NDefines.NAI.NEIGHBOUR_WAR_THREAT_FACTOR = 1.30 		-- How much increase in threat does AI feel against neighbours who are at war
NDefines.NAI.NEUTRAL_THREAT_PARANOIA = 20				-- How scared neutrals are of everyone
NDefines.NAI.DIFFERENT_FACTION_THREAT = 25				-- Threat caused by not being in the same faction

-- Avoice Equipment over-abundance
NDefines.NProduction.CAPITULATE_STOCKPILES_RATIO = 0.07 -- How much equipment from deployed divisions will be transferred on capitulation

-- Division Designer
NDefines.NMilitary.MAX_DIVISION_BRIGADE_WIDTH = 6			-- Max width of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_BRIGADE_HEIGHT = 4		-- Max height of regiments in division designer.
NDefines.NMilitary.MIN_DIVISION_BRIGADE_HEIGHT = 3		-- Min height of regiments in division designer.
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 5			-- Max width of support in division designer.
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 1		-- Max height of support in division designer.
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 300
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 100    		

-- Training divisions
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 40000	-- How many deployment lines minimum can be training
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.5

-- Speed at which scientists give spell points
NDefines.NProject.BREAKTHROUGH_DAILY_SCIENTIST_SKILL_GAIN = 16
NDefines.NProject.SCIENTIST_BASIC_RESEARCH_DAILY_XP_GAIN	= 0.35 -- vanilla is 0.28

-- Food consumption etc.
NDefines.NMilitary.ARMY_IDLE_FUEL_MULT = 0.05						-- fuel consumption ratio while just existing
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY	 = 2.0

-- Resistance
NDefines.NResistance.RESISTANCE_ACTIVITY_CHANCE_AT_MAX_RESISTANCE = 0.08 -- was 0.312
NDefines.NResistance.RESISTANCE_ACTIVITY_MIN_GARRISON_PENETRATE_CHANCE = 0.04 -- was 0.02
NDefines.NResistance.GARRISON_MANPOWER_REINFORCEMENT_SPEED = 300.0	-- Modifier for garrison manpower reinforcement.  This value is the maximum to be delivered which is then modified by distance, was 2000

NDefines.NResistance.RESISTANCE_POP_LOW_CUTOFF = 5000 -- was 10000
NDefines.NResistance.RESISTANCE_POP_VERY_LOW_CUTOFF = 500 -- was 1000

NDefines.NResistance.GARRISON_MANPOWER_LOST_BY_ATTACK = 0.009 	-- Ratio of manpower lost by garrison at each attack on garrison (this number will be reduced by the hardness of garrison template)
NDefines.NResistance.GARRISON_EQUIPMENT_LOST_BY_ATTACK = 0.013 	-- Ratio of equipment lost by garrison at each attack on garrison (this number will be reduced by the hardness of garrison template)
NDefines.NResistance.MAXIMUM_GARRISON_HARDNESS_WHEN_ATTACKED = 0.95   -- Cap to be sure that garrison will suffer lost in attack, even with a almost 100% hardness

NDefines.NResistance.FOREIGN_MANPOWER_MIN_THRESHOLD = 1000 -- was 5k

NDefines.NResistance.GARRISON_STR_POW_MANPOWER = 1.0 -- was 2
NDefines.NResistance.GARRISON_STR_POW_EQUIPMENT = 1.0 -- was 3

NDefines.NResistance.MIN_DAMAGE_TO_GARRISONS_MODIFIER = 0.05 -- was 0.1

-- QOL, unlimited units per general
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 999 -- (72) Divisions per general
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 999 -- Divisions per field marshal directly leading troop
NDefines.NMilitary.UNIT_LEADER_USE_NONLINEAR_XP_GAIN = false -- faster general grind

NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST	= 0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0	
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST= 0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST	= 0

-- Supply definers stolen from tzarmod belwo
NDefines.NCountry.VP_TO_SUPPLY_BASE = 1.5
NDefines.NAir.SUPPLY_NEED_FACTOR = 0.01
NDefines.NMilitary.MAX_OUT_OF_SUPPLY_DAYS = 22 -- (30)
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.4  
NDefines.NCountry.EQUIPMENT_UPGRADE_CHUNK_MAX_SIZE = 1000			-- Maximum chunk size of equipment upgrade distribution per update.
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.8 
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 45.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.125
NDefines.NSupply.NODE_FLOW_BONUS_PER_RAIL_LEVEL = 0.00
NDefines.NSupply.NODE_INITIAL_SUPPLY_FLOW = 3.2   --vanilla 2.8
NDefines.NSupply.NODE_STARTING_PENALTY_PER_PROVINCE = 0.40   --vanilla 0.5
NDefines.NSupply.NODE_ADDED_PENALTY_PER_PROVINCE = 0.55 --vanilla 0.7
NDefines.NSupply.INFRA_TO_SUPPLY = 0.75							-- each level of infra gives this many supply
NDefines.NSupply.VP_TO_SUPPLY_BASE = 1.0							-- Bonus to supply from a VP, no matter the level
NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.05			-- Bonus to supply local supplies from Victory Points, multiplied by this aspect and rounded to closest integer
NDefines.NSupply.SUPPLY_FROM_DAMAGED_INFRA = 0.6         --0.15 vanilla      -- damaged infrastructure counts as this in supply calcs
NDefines.NSupply.SUPPLY_BASE_MULT = 0.2				
NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 25

NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 3 -- railways will be put on cooldown when they are captured by enemy and will not be usable during the cooldown
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CORE = 1	


--Division design xp cost is now 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0 -- 0xp, was 25
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0 -- 0xp, was 5
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0 -- 0xp, was 10
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 2 -- Number of support companies allowed per division
NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR	= 0.85 -- divison veterancy manpower loss multiplier, vanilla is 1.00

NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0 -- 0% consumger goods possible
NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 0.50 -- eagle cap adjustment

-- Base speed of manpower mobilization  #in 1/1000 of 1 %
NDefines.NCountry.BASE_MOBILIZATION_SPEED = 0.02 -- double that of avnilla

-- changing xp cost 
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE	 = 0.003 --vanilla is 0.0015, this is army xp from combat
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 9999             -- WAS 500
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 9999
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 9999



-- land combat target selection 
NDefines.NMilitary.COMBAT_VALUE_ORG_IMPORTANCE = 5 --vanilla is 1
NDefines.NMilitary.SOFT_ATTACK_TARGETING_FACTOR = 2.0	
NDefines.NMilitary.HARD_ATTACK_TARGETING_FACTOR = 4.0	 -- more likely for hard attack units to target units with hardness aka cav targets cav



NDefines.NMilitary.INFRA_ORG_IMPACT = 0.25				-- scale factor of infra on org regain.
NDefines.NMilitary.LAND_SPEED_MODIFIER = 0.0375                    -- basic speed control

-- More days for inactive research and focus for QOL
NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 3.1  -- vanila is 2.0
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 50.0 -- Vanilla is 30.0, increased because ahead of time penalty also increased


NDefines.NMilitary.RETREAT_SPEED_FACTOR = 0.5    -- vanilla is 0.25
NDefines.NMilitary.WITHDRAWING_SPEED_FACTOR = 0.35   -- vanilla is 0.15
NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.3 
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01 
NDefines.NMilitary.REINFORCE_CHANCE = 0.05

NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.25
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.45
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = -0.175           -- small river crossing
NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.35     -- large river crossing
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2 -- vanilla 1, you can train to trained in deployment queue
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.15 -- combat bonus per veterancy level 
NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 156.0 -- vanilla 62.0  how fast you train in deployment queue
NDefines.NMilitary.BATALION_CHANGED_EXPERIENCE_DROP = 0 -- no vet loss when converting units


NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 15				-- WAS 30 | This many divisions are required for the country to be able to send volunteers.
NDefines.NDiplomacy.VOLUNTEERS_RETURN_EQUIPMENT = 1		-- Returning volunteers keep this much equipment
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 0			-- days to transfer a unit to another nation
